FROM ubuntu:latest

# Install Python and npm
RUN apt-get update && \
    apt-get install -y python3 python3-pip nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy application code
COPY . /app

# Install Python dependencies (if any)
RUN pip3 install -r python_requirements.txt

# Install npm dependencies (if any)
RUN npm install

# Build the c files. 
RUN node_modules/tree-sitter-cli/tree-sitter generate

# Build the SO file after the c files are generated. 
RUN gcc -o medfordparser.so -shared src/parser.c -I ./src -fPIC


# Expose port (if needed)
EXPOSE 8000

# Set the command to run your application
CMD ["python3", "python_sample.py"] 